# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 533438ce9db412058b6f5046457740b43d95e55690796aa56a1b6c603c8029763ea24b262ac44d7042e863f23bd990c9a936565d1c32be53ea7ebc017c26e3d0

test:
  secret_key_base: c07675ea137e9e6f8b5963ad1c64289e9f094b2c57700dfba9358257cf40203ac60f36d6b903e867eb73294735b291e63a8bd8966a3df56ba9971cf3a160691e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
